server {
    listen 80;
    server_name _; # Cambiar '_' por el dominio real cuando esté configurado (ej: admin.dulceruth.com)

    # Vital para los assets pesados de Marketing (imágenes crudas y videos Lottie nativos)
    client_max_body_size 100M;

    # Logs opcionales para debugging
    access_log /var/log/nginx/strapi-access.log;
    error_log /var/log/nginx/strapi-error.log;

    location / {
        proxy_pass http://localhost:1337;
        
        # Soportar WebSockets (útil en panel moderno u otras funciones realtime)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Proxy Headers
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Desactivando el bypass de proxy caché para Websockets
        proxy_cache_bypass $http_upgrade;
    }
}
